# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: 2
builds:
  -
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
nfpms:
  - vendor: rivosinc
    maintainer: abhinavDhulipal
    contents:
      - src: packaging/prometheus-slurm-exporter.service
        dst: /usr/lib/systemd/system/prometheus-slurm-exporter.service
        file_info:
          mode: 0644
          group: root
          owner: root
    scripts:
      postinstall: "packaging/postinstall.sh"
      preremove: "packaging/preremove.sh"
      postremove: "packaging/postremove.sh"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
