# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: 2
builds:
  -
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
nfpms:
  - vendor: rivosinc
    maintainer: abhinavDhulipala
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux